export interface DataSourceInfo {
  id: string;
  name: string;
  provider: string;
  status: 'integrated' | 'pending' | 'partial';
  whatItProvides: string;
  updateCadence?: string;
  methodologyLink?: string;
  attributionText: string;
  honestyCaveat?: string;    // extra truthfulness note shown in UI when present
}

export const DATA_SOURCES: DataSourceInfo[] = [
  {
    id: 'gemini-soil-advisor',
    name: 'Kisan Regenerative Agronomy Engine (Gemini)',
    provider: 'Kisan Intelligence Advisory Backend',
    status: 'integrated',
    whatItProvides: 'Agro-climatic zone classification, soil deficit analysis, organic biological amendments, and resilient crop rotation recommendations.',
    updateCadence: 'On-demand calculation per field input',
    attributionText: 'Analysis / Recommendation: Generated by Kisan Sahayak AI',
  },
  {
    id: 'gemini-leaf-diagnostics',
    name: 'Multimodal Crop Leaf Pathology Engine (Gemini)',
    provider: 'Kisan Multimodal Vision Diagnostic Service',
    status: 'integrated',
    whatItProvides: 'Visual symptom detection, causal pathogen classification, non-chemical eco-friendly remedies, and cultural prevention measures.',
    updateCadence: 'On-demand real-time photo inference',
    attributionText: 'Diagnostic Analysis: Generated by Kisan Sahayak AI',
  },
  {
    id: 'agro-climatic-gis',
    name: 'Agro-Climatic Zone GIS Boundaries',
    provider: 'Backend GIS Service (GET /api/v1/telemetry/agro-climatic-zones)',
    status: 'integrated',
    whatItProvides: 'GeoJSON FeatureCollection of agro-climatic zone boundary polygons. Currently serving 3 verified GIS features. Full Planning Commission or NARP zone coverage is not yet available.',
    updateCadence: 'Live on request (HTTP 200 verified)',
    attributionText: 'GIS data: Live backend endpoint confirmed operational',
    honestyCaveat: 'partialGisCoverage',
  },
  {
    id: 'imd-weather-telemetry',
    name: 'Field Weather & 7-Day Precipitation Outlook',
    provider: 'Meteorological Telemetry (Planned: IMD / Open-Meteo)',
    status: 'pending',
    whatItProvides: 'Local temperature, relative humidity, precipitation probability, and wind velocity.',
    attributionText: 'Not yet connected to live weather data feed',
  },
  {
    id: 'copernicus-sentinel-2',
    name: 'Sentinel-2 Satellite Multispectral Imagery (NDVI)',
    provider: 'ESA Copernicus Open Access Hub (Planned)',
    status: 'pending',
    whatItProvides: 'Direct Sentinel-2 Level-2A satellite imagery and Normalized Difference Vegetation Index (NDVI) field-level vegetative vigor from actual satellite passes is NOT currently connected.',
    attributionText: 'Not yet connected to live Sentinel-2 satellite telemetry',
    honestyCaveat: 'sentinelEstimatedNote',
  },
];

