export interface DataSourceInfo {
  id: string;
  name: string;
  provider: string;
  status: 'integrated' | 'pending';
  whatItProvides: string;
  updateCadence?: string;
  methodologyLink?: string;
  attributionText: string;
}

export const DATA_SOURCES: DataSourceInfo[] = [
  {
    id: 'gemini-soil-advisor',
    name: 'Kisan Regenerative Agronomy Engine (Gemini)',
    provider: 'Kisan Intelligence Advisory Backend',
    status: 'integrated',
    whatItProvides: 'Agro-climatic zone classification, soil deficit analysis, organic biological amendments, and resilient crop rotation recommendations.',
    updateCadence: 'On-demand calculation per field input',
    attributionText: 'Analysis / Recommendation: Generated by Kisan Sahayak AI',
  },
  {
    id: 'gemini-leaf-diagnostics',
    name: 'Multimodal Crop Leaf Pathology Engine (Gemini)',
    provider: 'Kisan Multimodal Vision Diagnostic Service',
    status: 'integrated',
    whatItProvides: 'Visual symptom detection, causal pathogen classification, non-chemical eco-friendly remedies, and cultural prevention measures.',
    updateCadence: 'On-demand real-time photo inference',
    attributionText: 'Diagnostic Analysis: Generated by Kisan Sahayak AI',
  },
  {
    id: 'imd-weather-telemetry',
    name: 'Field Weather & 7-Day Precipitation Outlook',
    provider: 'Meteorological Telemetry (Planned: IMD / Open-Meteo)',
    status: 'pending',
    whatItProvides: 'Local temperature, relative humidity, precipitation probability, and wind velocity.',
    attributionText: 'Not yet connected to live weather data feed',
  },
  {
    id: 'copernicus-sentinel-2',
    name: 'Sentinel-2 Satellite Multispectral Imagery (NDVI)',
    provider: 'ESA Copernicus Open Access Hub (Planned)',
    status: 'pending',
    whatItProvides: 'Normalized Difference Vegetation Index (NDVI) field-level vegetative vigor and moisture dynamics.',
    attributionText: 'Not yet connected to live satellite telemetry',
  },
];
